version: '3'
services:
  mysql:
    image: mysql:8.0.30-debian 
    volumes:
      - ./data:/var/lib/mysql
      - ./init/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: '123456'      
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
networks: 
  default: 
      external: 
        name: ambiente